package AST.Enums;

public enum NodeEnum {
    ASSIGN,
    BLOCK,
    BLOCK_TYPE,
    BLUEPRINT,
    BLUEPRINT_TYPE,
    BUILD,
    CHAIN,
    CHANNEL_DECLARATIONS,
    DRAW,
    GROUP,
    CHANNEL_IN_MY,
    CHANNEL_IN_TYPE,
    OPERATION_TYPE,
    CHANNEL_OUT_MY,
    CHANNEL_OUT_TYPE,
    PARAMS,
    PROCEDURE_CALL,
    PROCEDURE,
    ROOT,
    SELECTOR,
    SIZE,
    SIZE_TYPE,
    SOURCE_TYPE
}
