/* The following code was generated by The Language Compiler 1.0.0 */

package AutoGen.CodeGen;

import CodeGeneration.DataFlow.Network.Nodes.Block;
import CodeGeneration.DataFlow.Network.Nodes.Blocks.AbstractBlock;
import CodeGeneration.DataFlow.Network.Nodes.SignalNodes.Channel;
import CodeGeneration.DataFlow.Network.Nodes.SignalNodes.Channels.ListChannel;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operation;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.NullaryOperation.Source;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.UnaryOperations.UnitWiseOperations._Tanh;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.UnaryOperations.UnitWiseOperations._Sigmoid;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.UnaryOperations.UnitWiseOperations._Relu;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.UnaryOperations.MatrixOperations.Transpose;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.UnitWiseOperations._Multiplication;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.UnitWiseOperations._Division;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.UnitWiseOperations._Subtraction;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.UnitWiseOperations._Addition;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.MatrixOperations.Multiplication;
import CodeGeneration.DataFlow.Network.Nodes.BlocksAndSignalNodes.Operations.BinaryOperations.MatrixOperations.Multiplication;
import DataStructures.Pair;

public class Layer extends AbstractBlock {

    public Layer() {
        this.blueprint();
    }

    private void blueprint() {
        try {
            this.addNewInputLabel("in", new ListChannel());
            this.addNewOutputLabel("out", new ListChannel());
            Source weights;
            weights = (Source) new Source(new Pair<Integer, Integer>(1000, 1000));
            Source bias;
            bias = (Source) new Source(new Pair<Integer, Integer>(1000, 1000));
            Operation mult;
            mult = (Operation) new Multiplication();
            mult.receiveGroupConnection(this.getChannel("in"), weights);
            Block __Addition_514727072;
            __Addition_514727072 = new _Addition();
            Block __Sigmoid_311015504;
            __Sigmoid_311015504 = new _Sigmoid();
            __Addition_514727072.receiveGroupConnection(mult, bias);
            __Sigmoid_311015504.receiveGroupConnection(__Addition_514727072);
            __Sigmoid_311015504.connectTo(this.getChannel("out"));

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}